/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <tasks.h>
#include "stm32f303xc.h"




#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


// enable the clocks for desired peripherals (GPIOA, C and E)
void enable_clocks() {

	RCC->AHBENR |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOCEN | RCC_AHBENR_GPIOEEN;
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;

}

// initialise the discovery board I/O (just outputs: inputs are selected by default)
void initialise_board() {

	// get a pointer to the second half word of the MODER register (for outputs pe8-15)
	uint16_t *led_output_registers = ((uint16_t *)&(GPIOE->MODER)) + 1;
	*led_output_registers = 0x5555;

}

void led_callback(void) {
    static uint8_t led_state = 0;  // 0 = OFF, 1 = ON
    uint8_t *led_output_register = ((uint8_t*)&(GPIOE->ODR)) + 1;

    if (led_state == 0) {
        *led_output_register = 0b01010101;  // Turn LEDs ON
        led_state = 1;  // Next time, turn OFF
    } else {
        *led_output_register = 0x00;        // Turn LEDs OFF
        led_state = 0;  // Next time, turn ON
    }
}

void led_oneshot_callback(void) {

    uint8_t *led_output_register = ((uint8_t*)&(GPIOE->ODR)) + 1;
    *led_output_register = 0b10101010;  // Turn LEDs ON

}



//  general purpose timer registers page 647
int main(void)
{

	enable_clocks();
	initialise_board();

	// PART A
	Timer_Init(500, led_callback);	/// put in interval in ms


	while(1) {
		Timer_Update();

		static uint32_t counter = 0;
		counter++;

		//if(counter == 1200000) {
		//	Timer_SetPeriod(2000);
			//Timer_OneShot(3000, led_oneshot_callback);	// not working right now fix

		//}

	}


}
